spring:
  application:
    name: eurka-server

server:
  port: 8761

eureka:
  server:
    eviction-interval-timer-in-ms: 3000
    response-cache-update-interval-ms: 3000
  instance:
      hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


